repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        exclude: ^alembic/versions/
        args: [ --fix ]
      - id: ruff-format
        exclude: ^alembic/versions/


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: ^alembic/versions/


