version: '3.9'

services:
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command:
      ./start.sh
    volumes:
      - .:/app
      

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7.4-rc1
    container_name: redis_db
    environment:
      REDIS_HOST: localhost
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/var/lib/redis/data

