"""databasecheck

Revision ID: 1e2aff1b06ad
Revises: 3dfeb24d718f
Create Date: 2024-05-26 21:54:59.680595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2aff1b06ad'
down_revision: Union[str, None] = '3dfeb24d718f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
